# Matrices  

Olagoke Oladokun  
Covenant University, Ota, Nigeria  

©2021  


## GEC220  
## Engineering Mathematics II  


Matrices and Determinants: Solution of system of linear equations by determinants. Linear dependence and independence, rank of a matrix. General system of linear equations, existence and properties of solution, Gaussian elimination. Matrix inverse by elementary matrices, adjoint, and partitioning methods. Characteristic polynomial, characteristic equation, eigenvalues and eigenvectors.  



 
GEC220
Engineering Mathematics II 
3 Units
LH 45
Lecturers
	Prof. Vincent 
	Dr. Adeeyo
	Dr. Olagoke

Partial Differentiation: Functions of several variables, continuity and partial derivatives. Total differentials, approximate calculations using differentials. Chain rule. Implicit differentiation. Series representation of functions (Maclaurin & Taylor’s), Taylor’s Theorem. Extremum problems, (analytic method) without and with constraints, Lagrange multipliers, global extremum. Ordinary Differential Equations: Definition, degree, order, linear, non-linear, solution. First order equations, separable variables, equations reducible to separable form, exact equations, integrating factors, homogenous differential equations. Modeling of engineering systems leading to first order differential equations- electric circuit, mixing/dilution, radioactive decay, bacterial culture. 2nd order differential equations with constant coefficients, homogeneous, non-homogeneous, complementary functions, particular integrals, D-operator method. General linear second-order differential equations (without using matrices). Power series solution, Legendre’s differential equation. Modeling of engineering systems leading to 2nd order differential equations- electric circuit, mechanical oscillations-free and forced, resonance. Pre-requisites: MAT 121 and MAT 122.
Matrices and Determinants: Solution of system of linear equations by determinants. Linear dependence and independence, rank of a matrix. General system of linear equations, existence and properties of solution, Gaussian elimination. Matrix inverse by elementary matrices, adjoint, and partitioning methods. Characteristic polynomial, characteristic equation, eigenvalues and eigenvectors.


Contents
1	Matrices	6
1.1	Matrix notation	7
1.2	Addition and Subtraction of Matrices	7
1.3	Multiplication of Matrices	8
1.3.1	Scalar Multiplication	8
1.3.2	Two matrices multiplication	8
1.4	Transpose of matrix	10
1.5	Square matrix	10
1.5.1	Symmetry matrix	10
1.6	Triangular matrix	11
1.7	Diagonal matrix	11
1.8	Unit matrix	11
1.9	Null matrix	12
2	Determinants	13
2.1	Determinants of the second order	13
2.2	Determinants of the third order	14
3	Solution of system of linear equations by determinants	17
3.1	Determinant Equation Method	18
3.1.1	Secondary Degree	18
3.1.2	Third Degree	19
3.2	Cramers Rule	22
3.2.1	For second degree	22
3.2.2	Third degree	22
4	Linear dependence and independence	25
5	Rank of a matrix	27
6	General system of linear equations,	28
7	Existence and properties of solution	31
7.1	Existence of solution	31
7.2	Other properties of the solution	31
8	Gaussian elimination.	33
8.1	Algorithm of Gaussian Elimination	33
8.2	Determinant from Gaussian Elimination	38
9	Matrix inverse by elementary matrices, adjoint, and partitioning methods.	39
9.1	Inverse of a square matrix	39
9.2	Cofactors	39
9.3	Adjoint	41
10	Eigenvalues and Eigenvectors.	43
10.1	Eigenvalues	43
10.1.1	Example	43
10.2	Eigenvectors	44
10.2.1	Example	44


# Matrices

A matrix is a set of real or complex numbers (or elements) arranged in rows and columns to form a rectangular array.
A matrix can be identified by its order denoted as $m \times n \quad (m \ by \ n)$ matrix.  

$$
\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]	
$$  

What is the order of matrix above?. Matrix  has order $3\times 3$. The number of rows of A, $m = 3$ and number of column, $n = 3$  


In [42]:
import numpy as np

A = np.array([
    [3,-3,-4],
    [1,-1,-1],
    [2,-1,4]
])

print('===============================')
print('matrix A =')
print(A)
print()
print('mxn =', np.shape(A))
print('===============================')

matrix A =
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]]

mxn = (3, 3)


Similarly, the matrix $C$ below is of order $4\times2$  

$$
\left[\begin{matrix}\begin{matrix}1&2\\\end{matrix}\\\begin{matrix}4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2	
$$
$$
C=\left[\begin{matrix}\begin{matrix}1&2\\\end{matrix}\\\begin{matrix}4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2	
$$

In [43]:
import numpy as np

C = np.array([
    [1,2], [4,3],[-1,-5], [3,3],
])

print('===============================')
print('matrix C =\n', C)
print()
print('mxn =', np.shape(C))
print('===============================')


matrix C =
 [[ 1  2]
 [ 4  3]
 [-1 -5]
 [ 3  3]]

mxn = (4, 2)


## Matrix notation  

$$
A=\left[
    \begin{matrix}
        a_{11}&a_{12}&a_{13}\\
        a_{21}&a_{22}&a_{23}\\
        a_{31}&a_{32}&a_{33}\\
    \end{matrix}
    \right]	
$$
Matrix $A$ is of order $3 \times 3$ with elements $a_{ij}$ where $i$ and $j$ represents the index of the row and column it belongs in the matrix.

## Addition and Subtraction of Matrices

Addition and subtraction of two matrices can only be achieved if they are the same order.
$$
A\pm B
$$

Only possible if  
$$
\left.A\right|m{==}\left.B\right|m\ \\ and \\  \left.A\right|n{==}\left.B\right|n	
$$

Example

$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]	
$$
$$
B=\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]	
$$
Then 
Check the order of $A (2 \times 2)$ and compare to order $B (2 \times 2)$?
Since they are both equal the addition and subtraction is possible.

$$
\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]+\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]=\left[\begin{matrix}3&-6\\8.1&-6.5\\\end{matrix}\right]	
$$
$$
\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]-\left[\begin{matrix}2&-3\\4.1&-4.5\\\end{matrix}\right]=\left[\begin{matrix}-1&0\\-0.1&2.5\\\end{matrix}\right]	
$$



In [44]:
import numpy as np

A = np.array([[1,-3],[4,-2]])
B = np.array([[2,-3],[4.1,-4.5]])

sum = A + B
diff = A - B

print('============================')

print('sum = \n', sum)
print()
print('diff = \n', diff)

print('============================')


sum = 
 [[ 3.  -6. ]
 [ 8.1 -6.5]]

diff = 
 [[-1.   0. ]
 [-0.1  2.5]]


## Multiplication of Matrices  
### Scalar Multiplication

$$ 
4\times A= 4\times\left[
    \begin{matrix}
    1&-3 \\
    4&-2 \\
    \end{matrix}
    \right]
    =
    \left[
        \begin{matrix}
        4&-12\\
        16&-8\\
        \end{matrix}
    \right]
$$ 

In [45]:
import numpy as np

A = np.array(
    [
        [1, -3],
        [4, -2]
    ])

prod = 4*A

print('============================')
print('A= ')
print(A)
print('4*A =\n', prod)
print('============================')


A= 
[[ 1 -3]
 [ 4 -2]]
4*A =
 [[  4 -12]
 [ 16  -8]]


## Two matrices multiplication  
To multiply any two matrices the number of columns in the first matrix must be equal to the number of rows of the second matrix. The product matrix will have number of rows of the first matrix and number of columns of the second matrix
$$
A\times B =P
$$
Is possible if and only if
$$
    A|n == B|m \quad \Rightarrow \quad P=A|m\times B|n
$$

Example
$$
C=\left[\begin{matrix}\begin{matrix}1&2\\\end{matrix}\\\begin{matrix}4&3\\-1&-5\\3&3\\\end{matrix}\\\end{matrix}\right]=m\times n=4\times2	
$$
$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]=m\times n=2\times2
$$	

$$
A\times C \\
(2\times2)\ \times(4\times2) \\
2\times(2\neq4)\times2 
$$
  
$$
(2\neq4)∶\ A\times C \textrm{ is not possible.}
$$


In [46]:
import numpy as np

C = np.array(
    [
        [1,2],
        [4,3],
        [-1,-5],
        [3,3],
    ]
)

A = np.array(
    [
        [1,-3],
        [4,-2]
    ]
)

P = A @ C

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 2)

Interchanging 
$$
C\times A \\
(4\times2)\ \times(2\times2) \\
4\times(2=2)\times2 \\
$$
$$
(2=4)∶\ C\times A \textrm{ is possible.} \\
C\times A\equiv4\times2	
$$

Let’s carryout the multiplication.
$$
C\times A=\left[\begin{matrix}\begin{matrix}c_{11}&c_{12}\\\end{matrix}\\\begin{matrix}c_{21}&c_{22}\\c_{31}&c_{32}\\c_{41}&c_{42}\\\end{matrix}\\\end{matrix}\right]\times\left[\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right]
$$

$$
C\times A=\left[\begin{matrix}\begin{matrix}c_{11}a_{11}+c_{12}a_{21}&c_{11}a_{12}+c_{12}a_{22}\\\end{matrix}\\\begin{matrix}c_{21}a_{11}+c_{22}a_{21}&c_{21}a_{12}+c_{22}a_{22}\\c_{31}a_{11}+c_{32}a_{21}&c_{31}a_{12}+c_{32}a_{22}\\c_{41}a_{11}+c_{42}a_{21}&c_{41}a_{12}+c_{42}a_{22}\\\end{matrix}\\\end{matrix}\right]	
$$

$$
C\times A=\left[\begin{matrix}\begin{matrix}1\times1+2\times4\ \ \ \ \ \ &1\times-3+2\times-2\\\end{matrix}\\\begin{matrix}4\times1+3\times4&4\times-3+3\times-2\\-1\times1+-5\times4&-1\times-3+-5\times-2\\3\times1+3\times4&3\times-3+3\times-2\\\end{matrix}\\\end{matrix}\right]=\left[\begin{matrix}\begin{matrix}9&-7\\\end{matrix}\\\begin{matrix}16&-18\\-21&13\\15&-15\\\end{matrix}\\\end{matrix}\right]	
$$

In [7]:
import numpy as np

C = np.array(
    [
        [1,2],
        [4,3],
        [-1,-5],
        [3,3],
    ]
)

A = np.array(
    [
        [1,-3],
        [4,-2]
    ]
)

P = C @ A

print('=========================')
print('P=\n', P)
print('=========================')


P=
 [[  9  -7]
 [ 16 -18]
 [-21  13]
 [ 15 -15]]


## Transpose of matrix
Interchanging the rows and columns of a matrix is called transpose.
$$
A=\left[\begin{matrix}1&-3\\4&-2\\\end{matrix}\right]	
$$
$$
A^T=\left[\begin{matrix}1&4\\-3&-2\\\end{matrix}\right]	
$$


In [11]:
import numpy as np

C = np.array(
    [
        [1,2],
        [4,3],
        [-1,-5],
        [3,3],
    ]
)

A = np.array(
    [
        [1,-3],
        [4,-2]
    ]
)

Atrp = np.transpose(A)

print('=========================')
print('A=\n', A)
print('A^T=\n', Atrp)
print()
print('C=\n', C)
print('C^T=\n', np.transpose(C))
print('=========================')


A=
 [[ 1 -3]
 [ 4 -2]]
A^T=
 [[ 1  4]
 [-3 -2]]

C=
 [[ 1  2]
 [ 4  3]
 [-1 -5]
 [ 3  3]]
C^T=
 [[ 1  4 -1  3]
 [ 2  3 -5  3]]


## Square matrix
Square matrix is a matrix of order $m \times m$ or $n \times n$. It contains same number of rows and columns.

$$
A=  \left[
        \begin{matrix}
            a_{11} & a_{12} & \cdots & a_{1n}\\
            a_{21} & a_{22} & \cdots & a_{2n}\\
            \vdots & \vdots & \ddots & \vdots \\
            a_{n1} & a_{n2} & \cdots & a_{nn}\\
        \end{matrix}
    \right]
    =n\times n
    =m\times m	
$$
$$
A=\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]=3\times3	
$$


In [13]:
import numpy as np

A = np.array(
    [
        [3,-3,-4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

Atrp = np.transpose(A)

print('=========================')
print('A=\n', A)
print('\nmxn= ', np.shape(A))
print()
print('A^T=\n', Atrp)
print('\nmxn= ', np.shape(Atrp))
print('=========================')


A=
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

mxn=  (3, 3)

A^T=
 [[ 3  1  2]
 [-3 -1 -1]
 [-4 -2  4]]

mxn=  (3, 3)


### Symmetry matrix 
A square matrix is symmetrical if   $a_{ij}=a_{ji}$, meaning $S=S^T$.
$$
S=\left[\begin{matrix}1&2&3\\2&4&5\\3&5&6\\\end{matrix}\right]	
$$
$$
S^T=\left[\begin{matrix}1&2&3\\2&4&5\\3&5&6\\\end{matrix}\right]	
$$

In [1]:
import numpy as np

A = np.array(
    [
        [3,-3,-4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

A_T = np.transpose(A)

S = np.array(
    [
        [1, 2, 3],
        [2, 4, 5],
        [3, 5, 6],
    ]
)

S_T = np.transpose(S)
print('=========================')
print('S=\n', S)
print('\nmxn= ', np.shape(S))
print()
print('S^T=\n', S_T)
print('\nmxn= ', np.shape(S_T))
print() 
print('S == S^T')
print(S == S_T)

print('=========================')

print('A=\n', A)
print('\nmxn= ', np.shape(A))
print()
print('A^T=\n', A_T)
print('\nmxn= ', np.shape(A_T))
print()
print('A == A^T')
print(A == A_T)
print('=========================')


S=
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

mxn=  (3, 3)

S^T=
 [[1 2 3]
 [2 4 5]
 [3 5 6]]

mxn=  (3, 3)

S == S^T
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
A=
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

mxn=  (3, 3)

A^T=
 [[ 3  1  2]
 [-3 -1 -1]
 [-4 -2  4]]

mxn=  (3, 3)

A == A^T
[[ True False False]
 [False  True False]
 [False False  True]]


### Triangular matrix
A triangular matrix is a square matrix with all elements below the leading diagonal equal to zero.
$$
A=\left[\begin{matrix}1&2&3\\0&4&5\\0&0&6\\\end{matrix}\right]	
$$

### Diagonal matrix
A diagonal matrix is a square matrix with all elements zero except the leading diagonal.
$$
A=\left[\begin{matrix}1&0&0\\0&4&0\\0&0&6\\\end{matrix}\right]	
$$

### Unit matrix
A Unit matrix is a special diagonal matrix with the leading diagonal element values all unity or ones. The unit matrix is denoted by I. 
$$
\mathbb{I}=\left[\begin{matrix}1&0&0\\0&1&0\\0&0&1\\\end{matrix}\right]	
$$


#### Useful property
A useful property
$$
A.I=I.A=A	
$$


In [2]:
import numpy as np

A = np.array(
    [
        [3,-3,-4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

I = np.identity(3)

print('=========================')
print('A =\n', A)
print()
print('I =\n', I)
print()
print('A * I=\n', A @ I)
print()
print('I * A=\n', I @ A)
print('=========================')


A =
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A * I=
 [[ 3. -3. -4.]
 [ 1. -1. -2.]
 [ 2. -1.  4.]]

I * A=
 [[ 3. -3. -4.]
 [ 1. -1. -2.]
 [ 2. -1.  4.]]


## Null matrix
A null matrix is one whose elements are all zero.
$$
N=\left[\begin{matrix}0&0&0\\0&0&0\\0&0&0\\\end{matrix}\right]	
$$

#### Useful property
A useful property
$$
A.B=0
$$
we cannot say $A=0$ or $B=0$	


In [3]:
import numpy as np

A = np.array(
    [
        [3,-3,-4],
        [1, -1, -2],
        [2, -1, 4],
    ]
)

N = np.zeros(3)

print('=========================')
print('A =\n', A)
print()
print('N =\n', N)
print()
print('A * N=\n', A @ N)
print()
print('N * A=\n', N @ A)
print('=========================')


A =
 [[ 3 -3 -4]
 [ 1 -1 -2]
 [ 2 -1  4]]

N =
 [0. 0. 0.]

A * N=
 [0. 0. 0.]

N * A=
 [0. 0. 0.]


# Determinants

The arrangement of numbers in an equal rows and columns bounded by a straight bar is called determinant.

$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|	
$$

## Determinants of the second order
The symbol above is determinant of a $2\times 2$ (two by two matrix) with element $a_{11}$ on row 1 and column 1 and $a_{12}$  is element on row 1 and column 2.  It means each element is identified by row and column number subscript $i \textrm{and} j: a_{ij}$.  

By definition,
$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|=a_{11}a_{22}-a_{12}a_{21}	
$$

To find determinant of 
$$
\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right| 
$$  

we must multiply the elements diagonally to form the product terms in the expansion: 

$$
\textrm{we multiply }
\left|
    \begin{matrix}
        a_{11} & \\
        & a_{22}\\
    \end{matrix}
\right| 

\textrm{ then subtract the product } 

\left|
    \begin{matrix}
         & a_{12}\\
        a_{21} & \\
    \end{matrix}
\right|
$$

Note:  
$a_{11}$ before $a_{12}$ i.e column 1 before 2.  

$$
\left|
    \begin{matrix}
        1 & -3\\
        4 & -2\\
    \end{matrix}
\right|
=(1)(-2)-(-3)(4)=-2+12=10	
$$

Or

$$
\left|
    \begin{matrix}
        1&\\
        &-2\\
    \end{matrix}
\right|
-
\left|
    \begin{matrix}
         & -3\\
        4 & \\
    \end{matrix}
\right|
= 1\times -2 --3\times 4 = 10	
$$


In [52]:
# create a function for 2x2 determinant
def det2(a):
    d = (a[0,0]*a[1,1]) - (a[0,1]*a[1,0])
    return d


In [53]:
import numpy as np
# create our own 2x2 determinant

a = np.array([
    [1,-3],
    [4,-2]
])

detA = det2(a)
print('determinant of \n', a, '=', detA)

determinant of 
 [[ 1 -3]
 [ 4 -2]] = 10


In [54]:
import numpy as np

A = np.array([
    [1,-3],
    [4,-2]
])

# using in-built function in numpy
detA = np.linalg.det(A)

print('determinant= ', detA)

determinant=  10.000000000000002


More example in class  

## Determinants of the third order
A determinant of the third order contains 3 rows and 3 columns.
$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|	
$$


In order to find the determinant of a higher order the matrix minor must be developed until second order is reached.
Developing each element in the first row minor:
$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|
\left|\begin{matrix}+&-&+\\& &\\&&\\\end{matrix}\right|	
$$

For $a_{11}$
$$
\left|\begin{matrix}a_{11}&&\\&a_{22}&a_{23}\\&a_{32}&a_{33}\\\end{matrix}\right|	
\begin{matrix}a_{11}\\\\\end{matrix}\left|\begin{matrix}a_{22}&a_{23}\\a_{32}&a_{33}\\\end{matrix}\right|=a_{11}\left(a_{22}a_{33}-a_{23}a_{32}\right)	
$$
For $a_{12}$
$$
\left|\begin{matrix}&a_{12}&\\a_{21}&&a_{23}\\a_{31}&&a_{33}\\\end{matrix}\right|	
\begin{matrix}{-a}_{12}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{23}\\a_{31}&a_{33}\\\end{matrix}\right|=-a_{12}\left(a_{21}a_{33}-a_{23}a_{31}\right)	
$$
For $a_{13}$
$$
\left|\begin{matrix}&&a_{13}\\a_{21}&a_{22}&\\a_{31}&a_{32}&\\\end{matrix}\right|	
\begin{matrix}a_{13}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{22}\\a_{31}&a_{32}\\\end{matrix}\right|=a_{13}\left(a_{21}a_{32}-a_{22}a_{31}\right)	
$$


Summing all together:
$$
\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|=\begin{matrix}a_{11}\\\\\end{matrix}\left|\begin{matrix}a_{22}&a_{23}\\a_{32}&a_{33}\\\end{matrix}\right|\begin{matrix}{-a}_{12}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{23}\\a_{31}&a_{33}\\\end{matrix}\right|\begin{matrix}{+a}_{13}\\\\\end{matrix}\left|\begin{matrix}a_{21}&a_{22}\\a_{31}&a_{32}\\\end{matrix}\right|	
$$

$$
\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|	
=\begin{matrix}3\\\\\end{matrix}\left|\begin{matrix}-1&-1\\-1&4\\\end{matrix}\right|\begin{matrix}-\\\\\end{matrix}\begin{matrix}-3\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&4\\\end{matrix}\right|\begin{matrix}+\\\\\end{matrix}\begin{matrix}-4\\\\\end{matrix}\left|\begin{matrix}1&-1\\2&-1\\\end{matrix}\right|	
$$
$$
=3\left((-1\times4)-(-1\times-1)\right)--3((1\times4)-(-1\times2))+-4((1\times-1)-(-1\times2))	
$$
$$
=3\left(-4-1\right)--3(4-(-2))+-4(-1-(-2))	
$$
$$
=3\left(-5\right)+3(6)-4(1)	
$$
$$
=-15+18-4=-1
$$

In [57]:
def det3(a):
    a11 = a[1:,1:]  
    a12 = a[1:, 0::2]
    a13 = a[1:, 0:2]

    det_a11 = a[0,0]*(det2(a11))
    det_a12 = a[0,1]*(det2(a12))
    det_a13 = a[0,2]*(det2(a13))

    print('===+det3=========')
    print('determinant of a11\n', a11, '=', det_a11)
    print('determinant of a12\n', a12, '=', det_a12)
    print('determinant of a13\n', a13, '=', det_a13)
    print('===-det3=========')

    return det_a11 - det_a12 + det_a13

In [58]:
import numpy as np

a = np.array([
    [3, -3, -4],
    [1, -1, -1],
    [2, -1, 4],
])

detA = det3(a)
print('\ndeterminant of a\n', a, '=', detA)

# using in-built function
print('\n In-built determinant =', np.linalg.det(a))


===+det3=========
determinant of a11
 [[-1 -1]
 [-1  4]] = -15
determinant of a12
 [[ 1 -1]
 [ 2  4]] = -18
determinant of a13
 [[ 1 -1]
 [ 2 -1]] = -4
===-det3=========

determinant of a
 [[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]] = -1

 In-built determinant = -0.9999999999999998


Try 
$$
\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|
$$

Answer  
$$
\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0
$$

In [61]:
import numpy as np

a = np.array([
    [2, 3, 4],
    [6, 1, 0],
    [2, 3, 4],
])

detA = det3(a)
print('\ndeterminant of a\n', a, '=', detA)

# using in-built function
print('\n In-built determinant =', np.linalg.det(a))

===+det3=========
determinant of a11
 [[1 0]
 [3 4]] = 8
determinant of a12
 [[6 0]
 [2 4]] = 72
determinant of a13
 [[6 1]
 [2 3]] = 64
===-det3=========

determinant of a
 [[2 3 4]
 [6 1 0]
 [2 3 4]] = 0

 In-built determinant = 0.0


# Solution of system of linear equations by determinants


A system of linear equations of the second degree of two unknowns can be written below: 
$$
a_{11}x+a_{12}y=b_1 \\
a_{21}x+a_{22}y=b_2 	
$$
and can further be written in matrices form as  
$$
\left[\begin{matrix}a_{11}&a_{11}\\a_{11}&a_{11}\\\end{matrix}\right]\ \ \left[\begin{matrix}x\\y\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\\end{matrix}\right]\ \ 
$$
$$	
A . x=b
$$	

Solving Simultaneous Equation
$$
2x + 3y = 10\\
4x + y = 1
$$ 	

By elimination and substitution 
$$
x=-\frac{7}{10},\quad y=\frac{38}{10}	
$$


## Determinant Equation Method
### Secondary Degree
$$
2x + 3y = 10\\
4x + y = 1
$$ 	
could be written as: 
$$
2x+3y-10=0 \quad \left(a\right) \\
4x+y-1=0 \quad \left(b\right)	
$$
and
$$
a_{11}x+a_{12}y+b_1=0 \quad \left(a\right) \\
a_{21}x+a_{22}y+b_2=0 \quad \left(b\right)	
$$

The solution
$$
\frac{x}{∆_1}=\frac{-y}{∆_2}=\frac{1}{∆_0}
$$
$$
x=\frac{∆_1}{∆_0}, \quad y=\frac{-∆_2}{∆_0}
$$
where
$$
∆_0=\left|
        \begin{matrix} 
            a_{11} & a_{12} \\ 
            a_{21} & a_{22}
        \end{matrix}
    \right|
,\quad
∆_1=\left|
        \begin{matrix} 
            a_{12} & b_{1} \\ 
            a_{22} & b_{2}
        \end{matrix}
    \right|
,\quad
∆_2=\left|
        \begin{matrix} 
            a_{11} & b_{1} \\ 
            a_{21} & b_{2}
        \end{matrix}
    \right|
$$

Solving Equation 
$$
2x+3y-10=0 \quad \left(a\right) \\
4x+y-1=0 \quad \left(b\right)	
$$
$$
∆_0=\left|
        \begin{matrix} 
            2 & 3 \\ 
            4 & 1
        \end{matrix}
    \right|
    =
    (2\times 1)-(3\times 4)=2-12=-10
$$
$$
∆_1=\left|
        \begin{matrix} 
            3 & -10 \\ 
            1 & -1
        \end{matrix}
    \right|
    =
    (3\times -1)-(-10 \times 1)=-3--10=7
$$
$$
∆_2=\left|
        \begin{matrix} 
            2 & -10 \\ 
            4 & -1
        \end{matrix}
    \right|
    =
    (2 \times -1)-(-10 \times 4)=-2--40=38
$$
$$
x=\frac{∆_1}{∆_0}=\frac{7}{-10} =\left. -\frac{7}{10} \right. \\    
y=\frac{-∆_2}{∆_0}=\left.-\frac{38}{-10}\right.=\frac{38}{10}
$$

In [62]:
a0 = np.array([
    [2, 3],
    [4, 1]
])
a1 = np.array([
    [3, -10],
    [1, -1]
])
a2 = np.array([
    [2, -10],
    [4, -1]
])

D0 = det2(a0)
D1 = det2(a1)
D2 = det2(a2)

x = D1 / D0
y = D2 / D0

print('a0=\n', a0, ', D0=',D0)
print('a1=\n', a1, ', D1=',D1)
print('a2=\n', a2, ', D2=',D2)
print()
print(f'x = {D1}/{D0} = {x}, y = {D2}/{D0} = {y}')


a0=
 [[2 3]
 [4 1]] , D0= -10
a1=
 [[  3 -10]
 [  1  -1]] , D1= 7
a2=
 [[  2 -10]
 [  4  -1]] , D2= 38

x = 7/-10 = -0.7, y = 38/-10 = -3.8


### The solution for higher degree system of linear equations are:
### For third degree:
$$
\frac {x}{∆_1} = \frac {-y}{∆_2} = \frac {z}{∆_2} = \frac {-1}{∆_0} 
$$
$$
x=\frac {-∆_1}{∆_0}, \quad  y=\frac {∆_2}{∆_0}, \quad z=\frac {-∆_3}{∆_0}
$$

Note: The positive and negative signs alternate as the degree increases.

### Third Degree
Solve 
$$
3x -3y-4z = 1 \\
x -y - z =2 \\
2x -y + 4y =3	
$$
Rearrange
$$
3x -3y -4z -1 = 0 \\
x- y- z -2 =0 \\
2x -y + 4z -3 =0
$$	


Extract the matrix of coefficients:	
$$
\begin{bmatrix}
    3 & -3 & -4 & -1 \\
    1 & -1 & -1 & -2 \\
    2 & -1 & 4 & -3 \\
\end{bmatrix}
$$

From earlier
$$
\Delta {_0}=
\left |
 \begin{matrix}
 3 & -3 & -4  \\
 1 & -1 & -1  \\
 2 & -1 & 4  \\
 \end{matrix}
\right |
 =-1
$$

Note: Please evaluate $\Delta{_0}$ to confirm

$$
\Delta {_1}=
\left |
 \begin{matrix}
 -3 & -4 & -1 \\
 -1 & -1 & -2 \\
 -1 & 4 & -3 \\
 \end{matrix}
\right | \\
=-3\left(3--8\right)--4(3-2)+-1(-4-1)	\\
=-3\left(11\right)+4(1)-(-5)=-24
$$

$$
\Delta {_2}=
\left |
 \begin{matrix}
    3  & -4 & -1 \\
    1  & -1 & -2 \\
    2  & 4 & -3 \\
 \end{matrix}
\right| \\
=3\left(3--8\right)--4(-3--4)+-1(4--2)	\\
=3\left(11\right)+4(1)-(6)=31 
$$

$$
\Delta{_3}=
\left |
\begin{matrix}
    3 & -3 & -1 \\
    1 & -1 & -2 \\
    2 & -1 & -3 \\
\end{matrix}
\right| \\
=3\left(3-2\right)--3(-3--4)+-1(-1--2)	\\
=3\left(1\right)+3(1)-(1)=5
$$

From 
$$
x=\frac {-∆_1}{∆_0}, \quad  y=\frac {∆_2}{∆_0}, \quad z=\frac {-∆_3}{∆_0}
$$
$$
x=\frac{-(-24)}{-1},\quad y=\frac{31}{-1},\quad z=\frac{-(5)}{-1}	
$$
$$
x=-24,\quad y=-31,\quad z=5	
$$


In [71]:
a0 = np.array([
    [3, -3,-4],
    [1, -1,-1],
    [2, -1, 4]
])

a1 = np.array([
    [-3,-4,-1],
    [-1,-1,-2],
    [-1, 4,-3]
])
a2 = np.array([
    [3,-4,-1],
    [1,-1,-2],
    [2, 4,-3]
])
a3 = np.array([
    [3, -3,-1],
    [1, -1,-2],
    [2, -1,-3]
])

print()
D0 = det3(a0)
print(f'a0=\n{a0}, D0= {D0}')

print()
D1 = det3(a1)
print(f'a1=\n{a1}, D1= {D1}')

print()
D2 = det3(a2)
print('a2=\n', a2, ', D2=',D2)

print()
D3 = det3(a3)
print('a3=\n', a3, ', D3=',D3)


x = -D1 / D0
y = D2 / D0
z = -D3 / D0

print()
print(f'x = {D1}/{D0} = {x}, y = {D2}/{D0} = {y}, z = {D3}/{D0} = {z}')



===+det3=========
determinant of a11
 [[-1 -1]
 [-1  4]] = -15
determinant of a12
 [[ 1 -1]
 [ 2  4]] = -18
determinant of a13
 [[ 1 -1]
 [ 2 -1]] = -4
===-det3=========
a0=
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]], D0= -1

===+det3=========
determinant of a11
 [[-1 -2]
 [ 4 -3]] = -33
determinant of a12
 [[-1 -2]
 [-1 -3]] = -4
determinant of a13
 [[-1 -1]
 [-1  4]] = 5
===-det3=========
a1=
[[-3 -4 -1]
 [-1 -1 -2]
 [-1  4 -3]], D1= -24

===+det3=========
determinant of a11
 [[-1 -2]
 [ 4 -3]] = 33
determinant of a12
 [[ 1 -2]
 [ 2 -3]] = -4
determinant of a13
 [[ 1 -1]
 [ 2  4]] = -6
===-det3=========
a2=
 [[ 3 -4 -1]
 [ 1 -1 -2]
 [ 2  4 -3]] , D2= 31

===+det3=========
determinant of a11
 [[-1 -2]
 [-1 -3]] = 3
determinant of a12
 [[ 1 -2]
 [ 2 -3]] = -3
determinant of a13
 [[ 1 -1]
 [ 2 -1]] = -1
===-det3=========
a3=
 [[ 3 -3 -1]
 [ 1 -1 -2]
 [ 2 -1 -3]] , D3= 5

x = -24/-1 = -24.0, y = 31/-1 = -31.0, z = 5/-1 = 5.0


## Cramers Rule


## For second degree
For a system of two linear equations in two unknowns $(x,\  y)$ given below:
$$
a_{11}x + a_{12}y = b_1 \\
a_{21}x + a_{22}y = b_2 	
$$


Cramer’s rule states that:
$$
x=\frac{\left|\begin{matrix}b_1&a_{12}\\b_2&a_{22}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|},\ \ \ \ y=\frac{\left|\begin{matrix}a_{11}&b_1\\a_{21}&b_2\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}\\a_{21}&a_{22}\\\end{matrix}\right|}\
$$ 	
The denominator is the determinant of the coefficients of $x$ and $y$. The numerator for $x$ is the determinant of coefficients matrix when coefficients of $x$ is replaced by $b$. Similarly, the numerator for $y$ is the determinant of coefficients matrix when coefficients of $y$ is replaced by $b$.

### Third degree
$$
a_{11}x+a_{12}y+a_{13}z=b_1 \\
a_{21}x+a_{22}y+a_{23}z=b_2 \\
a_{31}x+a_{32}y+a_{33}z=b_3	
$$
$$
x=\frac{\left|\begin{matrix}b_1&a_{12}&a_{13}\\b_2&a_{22}&a_{23}\\b_3&a_{32}&a_{33}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|},\quad y=?,\quad z=?	
$$

$$
y=\frac{\left|\begin{matrix}a_{11}&b_1&a_{13}\\a_{21}&b_2&a_{23}\\a_{31}&b_3&a_{33}\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|},\quad 	

z=\frac{\left|\begin{matrix}a_{11}&a_{12}&b_1\\a_{21}&a_{22}&b_2\\a_{31}&a_{32}&b_3\\\end{matrix}\right|}{\left|\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right|}
$$

The Cramer’s rule can be generalized:
$$
x=\frac{D_x}{D},\quad y=\frac{D_y}{D},\quad z=\frac{D_z}{D}
$$	

Solve
$$
3x -3y-4z= 1\\
x-y- z =2\\
2x-y+ 4y =3	
$$

$$
x=\frac{\left|\begin{matrix}1&-3&-4\\2&-1&-1\\3&-1&4\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{24}{-1}=-24	
$$


$$
y=\frac{\left|\begin{matrix}3&1&-4\\1&2&-1\\2&3&4\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{31}{-1}=-31	
$$


$$
z=\frac{\left|\begin{matrix}3&-3&1\\1&-1&2\\2&-1&3\\\end{matrix}\right|}{\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|}=\frac{-5}{-1}=5
$$

Note: For both the determinant Equation Method and Cramer’s rule. The determinant, $∆_0$ or $D$, the coefficients of the variables must not equal zero. 
$$
∆_0≠0;\quad D\neq0
$$


In [72]:
a0 = np.array([
    [3, -3,-4],
    [1, -1,-1],
    [2, -1, 4]
])

a1 = np.array([
    [1, -3, -4],
    [2, -1, -1],
    [3, -1, 4]
])
a2 = np.array([
    [3, 1, -4],
    [1, 2, -1],
    [2, 3, 4]
])
a3 = np.array([
    [3, -3, 1],
    [1, -1, 2],
    [2, -1, 3]
])

print()
D0 = det3(a0)
print(f'a0=\n{a0}, D0= {D0}')

print()
D1 = det3(a1)
print(f'a1=\n{a1}, D1= {D1}')

print()
D2 = det3(a2)
print('a2=\n', a2, ', D2=',D2)

print()
D3 = det3(a3)
print('a3=\n', a3, ', D3=',D3)


x = D1 / D0
y = D2 / D0
z = D3 / D0

print()
print(f'x = {D1}/{D0} = {x}, y = {D2}/{D0} = {y}, z = {D3}/{D0} = {z}')



===+det3=========
determinant of a11
 [[-1 -1]
 [-1  4]] = -15
determinant of a12
 [[ 1 -1]
 [ 2  4]] = -18
determinant of a13
 [[ 1 -1]
 [ 2 -1]] = -4
===-det3=========
a0=
[[ 3 -3 -4]
 [ 1 -1 -1]
 [ 2 -1  4]], D0= -1

===+det3=========
determinant of a11
 [[-1 -1]
 [-1  4]] = -5
determinant of a12
 [[ 2 -1]
 [ 3  4]] = -33
determinant of a13
 [[ 2 -1]
 [ 3 -1]] = -4
===-det3=========
a1=
[[ 1 -3 -4]
 [ 2 -1 -1]
 [ 3 -1  4]], D1= 24

===+det3=========
determinant of a11
 [[ 2 -1]
 [ 3  4]] = 33
determinant of a12
 [[ 1 -1]
 [ 2  4]] = 6
determinant of a13
 [[1 2]
 [2 3]] = 4
===-det3=========
a2=
 [[ 3  1 -4]
 [ 1  2 -1]
 [ 2  3  4]] , D2= 31

===+det3=========
determinant of a11
 [[-1  2]
 [-1  3]] = -3
determinant of a12
 [[1 2]
 [2 3]] = 3
determinant of a13
 [[ 1 -1]
 [ 2 -1]] = 1
===-det3=========
a3=
 [[ 3 -3  1]
 [ 1 -1  2]
 [ 2 -1  3]] , D3= -5

x = 24/-1 = -24.0, y = 31/-1 = -31.0, z = -5/-1 = 5.0


In [ ]:
#Linear dependence and independence
	

A matrix is said to be linearly dependent if the determinant is zero and linearly independent if the determinant is not zero.
Linear dependence
$$
D=\left|A\right|=\ 0	
$$
And Linear independence
$$
D=\left|A\right|\neq\ 0
$$

In [4]:
Check if the matrices below are linear dependence or independence:
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|	
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|	

What is your answer?
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0	
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1	




 

 

Rank of a matrix
The rank of an m x n matrix A is the order of the largest square, linear independence sub-matrix. In order to get a matrix rank you must get a non-zero determinant matrix of the original m x n matrix or a sub-matrix.

Check the rank of matrix B below:
B=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1	
Since the determinant is non-zero the rank = 3.

Similarly, check for matrix A.
A=\left|\begin{matrix}2&3&4\\6&1&0\\2&3&4\\\end{matrix}\right|=0	
The determinant is zero, we need to check for the determinant of its sub-matrix:
A_1=\left|\begin{matrix}2&3\\6&1\\\end{matrix}\right|=-16	
Since the determinant of the sub-matrix A1 is non-zero, we can conclude that matrix A is of rank =2.


 

 

General system of linear equations, 
A system linear of equations below with three unknown x, y, z:
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1\ \ \ \ \bigma_{21}x_1+a_{22}x_2+a_{23}x_3=b_2\bigma_{31}x_1+a_{32}x_2+a_{33}x_3=b_3	
can be represented using matrix notation:
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\b_3\\\end{matrix}\right]	

Similarly,
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1\ \ \ \ \bigma_{21}x_1+a_{22}x_2+a_{23}x_3=b_2	
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\\end{matrix}\right]	


Generally,
\begin{matrix}\begin{matrix}\begin{matrix}a_{11}x_1\\a_{21}x_1\\a_{31}x_1\\\end{matrix}&\begin{matrix}a_{12}x_2\\a_{22}x_2\\a_{32}x_2\\\end{matrix}&\begin{matrix}a_{13}x_3\\a_{23}x_3\\a_{33}x_3\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}\begin{matrix}a_{1n}x_n&=&b_1\\\end{matrix}\\\begin{matrix}a_{2n}x_n&=&b_1\\\end{matrix}\\\begin{matrix}a_{3n}x_n&=&b_1\\\end{matrix}\\\end{matrix}\\\begin{matrix}\vdots\ \ \ \ \ &\ \ \ \vdots\ \ &\ \ \ \ \ \ \ \ \vdots\\\end{matrix}&&\ \ \ \begin{matrix}\vdots&&\ \ \ \ \ \ \vdots\\\end{matrix}\\\begin{matrix}a_{m1}x_1&a_{m2}x_2&a_{m3}x_3\\\end{matrix}&\ldots&\begin{matrix}a_{mn}x_n&=&b_m\\\end{matrix}\\\end{matrix}	
\left[\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{m1}&a_{m2}&a_{m3}\\\end{matrix}&\ldots&a_{mn}\\\end{matrix}\right]\left[\begin{matrix}x_1\\\begin{matrix}x_2\\x_3\\\vdots\\\end{matrix}\\x_n\\\end{matrix}\right]=\left[\begin{matrix}b_1\\\begin{matrix}b_2\\b_3\\\vdots\\\end{matrix}\\b_m\\\end{matrix}\right]	
A\bullet x=b	
where
A=\left[\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{m1}&a_{m2}&a_{m3}\\\end{matrix}&\ldots&a_{mn}\\\end{matrix}\right];\ \ x=\left[\begin{matrix}x_1\\\begin{matrix}x_2\\x_3\\\vdots\\\end{matrix}\\x_n\\\end{matrix}\right];\ \ b=\left[\begin{matrix}b_1\\\begin{matrix}b_2\\b_3\\\vdots\\\end{matrix}\\b_m\\\end{matrix}\right]	
If we multiply Eq (6.7) by A-1 the inverse of A. 
A^{-1}.A.x=A^{-1}.b	
A^{-1}.A=\mathbit{I}	
\mathbit{I}.x=A^{-1}.b	
x=A^{-1}.b	
and	
A^{-1}=\frac{C^T}{\left|A\right|}	


 

 

Existence and properties of solution
Existence of solution
Looking at the equations below:
A.x=b	
x=A^{-1}.b	
A^{-1}=\frac{C^T}{\left|A\right|}	
Forming an augmented matrix A_b.
A_b.=[A|b]	

For a solution to exist for a set of linear equations the following must be true:
	Determinant of A must not be equal to zero, i.e \left|A\right|\neq0. 
	A unique solution exists:
rank\ of\ A=rank\ of\ A_b=n
	An infinite number of solutions exist:
rank\ of\ A=rank\ of\ A_b=m<n
	No solution exists:
rank\ A<rank\ A_b
Other properties of the solution
x=0,\ \ A^{-1}=0\ or\ b=0	

 

 

Gaussian elimination. 
Algorithm of Gaussian Elimination
Gaussian elimination method converts the combine matrix of A and b, [A|b] to triangular matrix. Then proceed with backward substitution to obtain x.
For a system of linear equations
a_{11}x_1+a_{12}x_2+a_{13}x_3=b_1\ \ \ \ \bigma_{21}x_1+a_{22}x_2+a_{23}x_3=b_2\bigma_{31}x_1+a_{32}x_2+a_{33}x_3=b_3	

Step 1: Write in matrix form.
\left[\begin{matrix}a_{11}&a_{12}&a_{13}\\a_{21}&a_{22}&a_{23}\\a_{31}&a_{32}&a_{33}\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\x_3\\\end{matrix}\right]=\left[\begin{matrix}b_1\\b_2\\b_3\\\end{matrix}\right]	
A\bullet x=b	

Step 2: Arrange matrix A and b together to form augmented matrix A_b.
A_b=\left[A|b\right]	
A_b=\left[\begin{matrix}a_{11}&a_{12}&\begin{matrix}a_{13}&|&b_1\\\end{matrix}\\a_{21}&a_{22}&\begin{matrix}a_{23}&|&b_2\\\end{matrix}\\a_{31}&a_{32}&\begin{matrix}a_{33}&|&b_3\\\end{matrix}\\\end{matrix}\right]	
Step 3: Using matrix row equivalent operation reduce A_b to triangular matrix \widetilde{A_b}.
A_b\rightarrow\widetilde{A_b}	
\left[\begin{matrix}a_{11}&a_{12}&\begin{matrix}a_{13}&|&b_1\\\end{matrix}\\a_{21}&a_{22}&\begin{matrix}a_{23}&|&b_2\\\end{matrix}\\a_{31}&a_{32}&\begin{matrix}a_{33}&|&b_3\\\end{matrix}\\\end{matrix}\right]\rightarrow\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]	
\widetilde{M}=\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]	
Step 4: Back substitution
\begin{matrix}\begin{matrix}{\widetilde{a}}_{11}x_1&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{12}x_2&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{13}x_3&=&{\widetilde{b}}_1\\\end{matrix}\\&\begin{matrix}{\widetilde{a}}_{22}x_2&+\\\end{matrix}&\begin{matrix}{\widetilde{a}}_{23}x_3&=&{\widetilde{b}}_2\\\end{matrix}\\&&\begin{matrix}{\widetilde{a}}_{33}x_3&=&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}	
\begin{matrix}x_3&=&\sfrac{{\widetilde{b}}_3}{{\widetilde{a}}_{33}}\\\end{matrix}	
\begin{matrix}x_2&=&\frac{{\widetilde{b}}_2-{\widetilde{a}}_{23}x_3}{{\widetilde{a}}_{22}}\\\end{matrix}	
\begin{matrix}x_1&=&\frac{{\widetilde{b}}_1-{\widetilde{a}}_{12}x_2-{\widetilde{a}}_{13}x_3}{{\widetilde{a}}_{11}}\\\end{matrix}	

Solve the set of equations.
3x\ -3y-4z=\ 1\bigmx-y-\ z\ \ \ \ \ \ \ =2\bigm2x-y+\ 4y\ \ \ =3	
Step 1: Write in matrix form.
A\bullet x=b	
\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}1\\2\\3\\\end{matrix}\right]	

Step 2: Arrange matrix A and b together augmented matrix A_b.
A_b=\left[A|b\right]	
A_b=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\1&-1&\begin{matrix}-1&|&2\\\end{matrix}\\2&-1&\begin{matrix}\ \ \ 4&|&3\\\end{matrix}\\\end{matrix}\right]	
Step 3: Using matrix row equivalent operation reduce M to triangular matrix \widetilde{M}.
A_b\rightarrow\widetilde{A_b}	
pivot,\ p=1,\ldots,\ m-1\ 
i=p+1,\ ...,\ m\ \ \ \ 
Note: 
a_{pp}\neq0\ \ \ \ 
If a_{pp}\neq0\ \ \ \ \ interchange\ row\ with\ a\ none-zero\ pivot\ column\ element.	
R_i\ =R_i-\left(R_p\times\ \frac{a_{ip}}{a_{pp}}\right)\ \ \ 	

p=1,...,2;\ i=2,...,3	
Reduce {\widetilde{A_b}}_{p=1}
\ p=1;\ i=2	
a_{pp}=a_{11}=3\ \ \ \ 	
R_2=\left[\begin{matrix}1&-1&\begin{matrix}-1&|&2\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\\end{matrix}\right]\times\frac{1}{3}\right)=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]	
p=1;\ i=3\ \ \ \ 	
R_3=\left[\begin{matrix}2&-1&\begin{matrix}4&|&3\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\\end{matrix}\right]\times\frac{2}{3}\right)=\left[\begin{matrix}0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]	
{\widetilde{A_b}}_{p=1}=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]	
Reduce {\widetilde{A_b}}_{p=2}
p=2;\ i=3\ \ \ \ 	
a_{pp}=a_{22}=0\ \ \ \ 	
Interchange row 2 and 3
{\widetilde{A_b}}_{p=1}=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]	
\ p=2;\ i=3\ \ \ \ 	
a_{pp}=a_{22}=1\ \ \ \ 	
R_3=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]-\left(\left[\begin{matrix}0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\\end{matrix}\right]\times\frac{0}{1}\right)=\left[\begin{matrix}0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]	
{\widetilde{A_b}}_{p=2}=\left[\begin{matrix}3&-3&\begin{matrix}-4&|&1\\\end{matrix}\\0&1&\begin{matrix}6.67&|&2.33\\\end{matrix}\\0&0&\begin{matrix}0.33&|&1.67\\\end{matrix}\\\end{matrix}\right]	

Step 4: Back substitution
\begin{matrix}\begin{matrix}3x_1&-\\\end{matrix}&\begin{matrix}3x_2&-\\\end{matrix}&\begin{matrix}4x_3&=&1\\\end{matrix}\\&\begin{matrix}x_2&+\\\end{matrix}&\begin{matrix}6.67x_3&=&2.33\\\end{matrix}\\&&\begin{matrix}0.33x_3&=&1.67\\\end{matrix}\\\end{matrix}	
\begin{matrix}x_3&=&\sfrac{1.67}{0.33}\\\end{matrix}=5.06	
\begin{matrix}x_2&=&\frac{2.33-6.67(5.06)}{1}\\\end{matrix}=-31.42	
\begin{matrix}x_1&=&\frac{1--3(-31.42)--4(5.06)}{3}\\\end{matrix}=-24.34	

Determinant from Gaussian Elimination 
\widetilde{A_b}=\left[\begin{matrix}{\widetilde{a}}_{11}&{\widetilde{a}}_{12}&\begin{matrix}{\widetilde{a}}_{13}&|&{\widetilde{b}}_1\\\end{matrix}\\0&{\widetilde{a}}_{22}&\begin{matrix}{\widetilde{a}}_{23}&|&{\widetilde{b}}_2\\\end{matrix}\\0&0&\begin{matrix}{\widetilde{a}}_{33}&|&{\widetilde{b}}_3\\\end{matrix}\\\end{matrix}\right]	
\left|A\right|={(-1)}^k\prod_{i}^{m}{\widetilde{a}}_{ii}={\widetilde{a}}_{11}\times{\widetilde{a}}_{22}\times{\widetilde{a}}_{33}	
where k is the number of times rows were interchanged.
From the example above and Eq (8.34)
\left|A\right|={(-1)}^1\prod_{i=1}^{m=3}{\widetilde{a}}_{ii}={(-1)}^1(3\times1\times0.33)=-0.99	


 

 

Matrix inverse by elementary matrices, adjoint, and partitioning methods. 
Inverse of a square matrix
Recall the solution to system of linear equation:
A.x=b	
x=A^{-1}.b	
A^{-1}=\frac{C^T}{\left|A\right|}	
To solve Eq (9.3) the inverse of matrix A, {(A}^{-1}) must be evaluated.
where C^Tis the adjoint of matrix A, and Adjoint is the transpose of the co-factor of matrix A.

Cofactors
Cofactor of a square matrix is obtained from the determinant of its elements.
\left|A\right|=\left|\begin{matrix}\begin{matrix}\begin{matrix}a_{11}\\a_{21}\\a_{31}\\\end{matrix}&\begin{matrix}a_{12}\\a_{22}\\a_{32}\\\end{matrix}&\begin{matrix}a_{13}\\a_{23}\\a_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}a_{1n}\\a_{2n}\\a_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}a_{n1}&a_{n2}&a_{n3}\\\end{matrix}&\ldots&a_{nn}\\\end{matrix}\right|	
Cofactor=\left[\begin{matrix}\begin{matrix}\begin{matrix}c_{11}\\c_{21}\\c_{31}\\\end{matrix}&\begin{matrix}c_{12}\\c_{22}\\c_{32}\\\end{matrix}&\begin{matrix}c_{13}\\c_{23}\\c_{33}\\\end{matrix}\\\end{matrix}&\begin{matrix}\ldots\\\ldots\\\ldots\\\end{matrix}&\begin{matrix}c_{1n}\\c_{2n}\\c_{3n}\\\end{matrix}\\\begin{matrix}\vdots\ \ &\ \ \ \vdots\ &\ \ \ \ \vdots\\\end{matrix}&&\vdots\\\begin{matrix}c_{n1}&c_{n2}&c_{n3}\\\end{matrix}&\ldots&c_{nn}\\\end{matrix}\right]	
where each element of the cofactor is formed from the determinant of its sub-matrix multiplied by element position sign. The element positional sign alternate between plus + and minus -.
Evaluate the cofactor of the matrix A below:
A=\left[\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right]	
For element a_{11}=3;
c_{11}=+\left|\begin{matrix}-1&-1\\-1&4\\\end{matrix}\right|=-5	
For element a_{12}=-3;
c_{12}=-\left|\begin{matrix}1&-1\\2&4\\\end{matrix}\right|=-6	
For element a_{13}=-4;
c_{13}=+\left|\begin{matrix}1&-1\\2&-1\\\end{matrix}\right|=1	
For element a_{21}=1;
c_{21}=-\left|\begin{matrix}-3&-4\\-1&4\\\end{matrix}\right|=16	
For element a_{22}=-1;
c_{22}=+\left|\begin{matrix}3&-4\\2&4\\\end{matrix}\right|=20	
For element a_{23}=-1;
c_{23}=-\left|\begin{matrix}3&-3\\2&-1\\\end{matrix}\right|=-3	
For element a_{31}=2;
c_{31}=+\left|\begin{matrix}-3&-4\\-1&-1\\\end{matrix}\right|=-1	
For element a_{32}=-1;
c_{32}=-\left|\begin{matrix}3&-4\\1&-1\\\end{matrix}\right|=-1	
For element a_{33}=4;
c_{13}=+\left|\begin{matrix}3&-3\\1&-1\\\end{matrix}\right|=0	
The cofactor form is:
Cofactor\ A=\left[\begin{matrix}-5&-6&1\\16&20&-3\\-1&-1&0\\\end{matrix}\right]	



Adjoint
Adjoint of matrix A is the transpose of the cofactor of A.
From Eq (9.16)
Adj\ A=C^T\ =\left[\begin{matrix}-5&16&-1\\-6&20&-1\\1&-3&0\\\end{matrix}\right]	

A^{-1}=\frac{C^T}{\left|A\right|}	
\left|A\right|=\left|\begin{matrix}3&-3&-4\\1&-1&-1\\2&-1&4\\\end{matrix}\right|=-1	
Therefore
A^{-1}=\frac{1}{-1}\left[\begin{matrix}-5&16&-1\\-6&20&-1\\1&-3&0\\\end{matrix}\right]=\left[\begin{matrix}5&-16&1\\6&-20&1\\-1&3&0\\\end{matrix}\right]	
To solve the system linear of equation
x=A^{-1}.b	
\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}5&-16&1\\6&-20&1\\-1&3&0\\\end{matrix}\right]\left[\begin{matrix}1\\2\\3\\\end{matrix}\right]
\left[\begin{matrix}x\\y\\z\\\end{matrix}\right]=\left[\begin{matrix}(5\times1)+(-16\times2)+(1\times3)\\(6\times1)+(-20\times2)+(1\times3)\\(-1\times1)+(3\times2)+(0\times3)\\\end{matrix}\right]=\left[\begin{matrix}-24\\-31\\5\\\end{matrix}\right]	


 

 

Eigenvalues and Eigenvectors.
Eigenvalues
Eigenvalues are characteristic scalar value (\lambda) of a square matrix (A) that satisfy the equation 10.1.
Ax=\lambda x	
In other to find the eigenvalues, we develop the characteristic equation and solve the characteristic polynomial of matrix A.
(A-\lambda\mathbit{I})x=0	
To prevent the trivial solution x\neq0. Therefore we have the characteristic equation Eq (10.3).
\left|A-\lambda\mathbit{I}\right|=0	
The solution of Eq (10.3) gives the eigenvalues \lambda.

Example
Find the eigenvalues of the matrix. 
A=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]	
A-\lambda\mathbit{I}=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]-\lambda\left[\begin{matrix}1&0\\0&1\\\end{matrix}\right]=\left[\begin{matrix}(2-\lambda)&3\\4&(1-\lambda)\\\end{matrix}\right]	
\left|A-\lambda\mathbit{I}\right|=\left|\begin{matrix}\left(2-\lambda\right)&3\\4&\left(1-\lambda\right)\\\end{matrix}\right|=\left(2-\lambda\right)\left(1-\lambda\right)-12=2-2\lambda-\lambda+\lambda^2-12
\left|A-\lambda\mathbit{I}\right|=\lambda^2-3\lambda-10=0	
The solutions to the characteristic polynomial in Eq 10.6
\lambda=-2\ or\ 5	
\lambda_1=-2,\ \ \lambda_2=5	

Eigenvectors
Each eigenvalues obtained has a corresponding eigenvector or eigenline associated with it.
Ax=\lambda x	
Example
When matrix A is:
A=\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]
\lambda_1=-2,\ \ \lambda_2=5	
For \lambda_1=-2
\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]=-2\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]	
\begin{matrix}\begin{matrix}2x_1&+\\\end{matrix}&\begin{matrix}3x_2&=\\\end{matrix}\ \ \\\begin{matrix}4x_1&+\\\end{matrix}&\begin{matrix}x_2&=\\\end{matrix}\\\end{matrix}\begin{matrix}{-2x}_1\\{-2x}_2\\\end{matrix}	
x_2=-\frac{4}{3}x_1	
The eigenvector for \lambda_1=-2
x_1=\left[\begin{matrix}k\\-{\frac{4}{3}}k\\\end{matrix}\right]\ and\ the\ smallest:\ x_1=\left[\begin{matrix}1\\-{\frac{4}{3}}\\\end{matrix}\right]	
For \lambda_2=5
\left[\begin{matrix}2&3\\4&1\\\end{matrix}\right]\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]=5\left[\begin{matrix}x_1\\x_2\\\end{matrix}\right]	
\begin{matrix}\begin{matrix}2x_1&+\\\end{matrix}&\begin{matrix}3x_2&=\\\end{matrix}\ \ \\\begin{matrix}4x_1&+\\\end{matrix}&\begin{matrix}x_2&=\\\end{matrix}\\\end{matrix}\begin{matrix}{5x}_1\\{5x}_2\\\end{matrix}	
x_2=x_1	
The eigenvector for \lambda_2=5
x_2=\left[\begin{matrix}k\\k\\\end{matrix}\right]\ and\ the\ smallest:\ x_2=\left[\begin{matrix}1\\1\\\end{matrix}\right]	



 



SyntaxError: invalid syntax (<ipython-input-4-eaab5783b539>, line 1)