In [130]:
import pandas as pd
from sklearn.feature_extraction import DictVectorizer

vec = DictVectorizer()

df = pd.read_excel('vehicle_emission.xls', index_col=0)
df_cols = df[['Make','Fuel', 'Vehicle','Use']]

dfw = df.copy()

for c in df_cols.columns:
    print(c)
    df1 = df_cols[[c]]
    dic1 = df1.to_dict('records')
    aMake =vec.fit_transform(dic1).toarray()
    df2 = pd.DataFrame(aMake)
    # start index
    df2.index += 1
    # rename columns
    df2.columns = [c + str(x)  for x in df2.columns]
    dfw = pd.concat([dfw, df2], axis=1)

dfw

Make
Fuel
Vehicle
Use


Make    Yr    Fuel Vehicle         Use  CO   CO2     O2   HC  Age  \
1       Honda  2006  Petrol     Car  Commercial   0  13.5   1.55    0    8   
2       Honda  2007  Petrol    Jeep  Commercial   0  14.7   0.08   10    7   
3      Toyota  2011  Petrol     Car  Commercial   0  14.6   0.72    1    3   
4      Toyota  1998  Petrol     Car    Official   0  10.2   3.15    1   16   
5      Toyota  2002  Petrol     Car    Official   0  14.5   0.60    1   12   
6      Toyota  2002  Petrol    Jeep    Official   0  12.9   1.52    4   12   
7       Honda  1993  Petrol     Car     Private   0  12.5   2.80   34   21   
8       Honda  1993  Petrol     Car     Private   0   5.3   5.30  697   21   
9   Volswagen  1994  Petrol     Car     Private   0  12.5  12.50    4   20   
10     Nissan  1997  Petrol    Jeep     Private   0  13.6   5.30    4   17   

    Make0  Make1  Make2  Make3  Fuel0  Vehicle0  Vehicle1  Use0  Use1  Use2  
1     1.0    0.0    0.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0  
2     1.0    0.0    0.0    0.0    1.0       0.0       1.0   1.0   0.0   0.0  
3     0.0    0.0    1.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0  
4     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0  
5     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0  
6     0.0    0.0    1.0    0.0    1.0       0.0       1.0   0.0   1.0   0.0  
7     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0  
8     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0  
9     0.0    0.0    0.0    1.0    1.0       1.0       0.0   0.0   0.0   1.0  
10    0.0    1.0    0.0    0.0    1.0       0.0       1.0   0.0   0.0   1.0

In [131]:
import sklearn.preprocessing as preprocessing

X = df[['Age','CO','CO2','O2','HC']].to_numpy()
X_normalized = preprocessing.normalize(X, norm='l2')
# 
df2 = pd.DataFrame(X_normalized)
# start index
df2.index += 1
df2.columns = ['Age0','CO20','CO20','O20','HC0']
dfw = pd.concat([dfw, df2], axis=1)

In [132]:
from sklearn.preprocessing import MinMaxScaler

data = df[['Age','CO','CO2','O2','HC']].to_numpy()

scaler = MinMaxScaler()
print(scaler.fit(data))
print((scaler.data_min_, scaler.data_max_))

data_normalized = scaler.transform(data)

data_normalized

MinMaxScaler()
(array([3.  , 0.  , 5.3 , 0.08, 0.  ]), array([ 21. ,   0. ,  14.7,  12.5, 697. ]))


array([[0.27777778, 0.        , 0.87234043, 0.11835749, 0.        ],
       [0.22222222, 0.        , 1.        , 0.        , 0.0143472 ],
       [0.        , 0.        , 0.9893617 , 0.05152979, 0.00143472],
       [0.72222222, 0.        , 0.5212766 , 0.24718196, 0.00143472],
       [0.5       , 0.        , 0.9787234 , 0.04186795, 0.00143472],
       [0.5       , 0.        , 0.80851064, 0.11594203, 0.00573888],
       [1.        , 0.        , 0.76595745, 0.21900161, 0.04878049],
       [1.        , 0.        , 0.        , 0.42028986, 1.        ],
       [0.94444444, 0.        , 0.76595745, 1.        , 0.00573888],
       [0.77777778, 0.        , 0.88297872, 0.42028986, 0.00573888]])

In [133]:
df2 = pd.DataFrame(data_normalized)

# start index
df2.index += 1
df2.columns = ['Age1','CO1','CO21','O21','HC1']
dfw = pd.concat([dfw, df2], axis=1)


In [134]:
dfw

Make    Yr    Fuel Vehicle         Use  CO   CO2     O2   HC  Age  \
1       Honda  2006  Petrol     Car  Commercial   0  13.5   1.55    0    8   
2       Honda  2007  Petrol    Jeep  Commercial   0  14.7   0.08   10    7   
3      Toyota  2011  Petrol     Car  Commercial   0  14.6   0.72    1    3   
4      Toyota  1998  Petrol     Car    Official   0  10.2   3.15    1   16   
5      Toyota  2002  Petrol     Car    Official   0  14.5   0.60    1   12   
6      Toyota  2002  Petrol    Jeep    Official   0  12.9   1.52    4   12   
7       Honda  1993  Petrol     Car     Private   0  12.5   2.80   34   21   
8       Honda  1993  Petrol     Car     Private   0   5.3   5.30  697   21   
9   Volswagen  1994  Petrol     Car     Private   0  12.5  12.50    4   20   
10     Nissan  1997  Petrol    Jeep     Private   0  13.6   5.30    4   17   

    ...      Age0  CO20      CO20       O20       HC0      Age1  CO1  \
1   ...  0.507334   0.0  0.856125  0.098296  0.000000  0.277778  0.0   
2   ...  0.366348   0.0  0.769332  0.004187  0.523355  0.222222  0.0   
3   ...  0.200590   0.0  0.976205  0.048142  0.066863  0.000000  0.0   
4   ...  0.830721   0.0  0.529584  0.163548  0.051920  0.722222  0.0   
5   ...  0.636347   0.0  0.768920  0.031817  0.053029  0.500000  0.0   
6   ...  0.661863   0.0  0.711502  0.083836  0.220621  0.500000  0.0   
7   ...  0.500413   0.0  0.297865  0.066722  0.810192  1.000000  0.0   
8   ...  0.030114   0.0  0.007600  0.007600  0.999489  1.000000  0.0   
9   ...  0.740995   0.0  0.463122  0.463122  0.148199  0.944444  0.0   
10  ...  0.746901   0.0  0.597521  0.232857  0.175741  0.777778  0.0   

        CO21       O21       HC1  
1   0.872340  0.118357  0.000000  
2   1.000000  0.000000  0.014347  
3   0.989362  0.051530  0.001435  
4   0.521277  0.247182  0.001435  
5   0.978723  0.041868  0.001435  
6   0.808511  0.115942  0.005739  
7   0.765957  0.219002  0.048780  
8   0.000000  0.420290  1.000000  
9   0.765957  1.000000  0.005739  
10  0.882979  0.420290  0.005739  

[10 rows x 30 columns]

In [135]:
x1 = dfw.iloc[:,10:20]
x1

Make0  Make1  Make2  Make3  Fuel0  Vehicle0  Vehicle1  Use0  Use1  Use2
1     1.0    0.0    0.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0
2     1.0    0.0    0.0    0.0    1.0       0.0       1.0   1.0   0.0   0.0
3     0.0    0.0    1.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0
4     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0
5     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0
6     0.0    0.0    1.0    0.0    1.0       0.0       1.0   0.0   1.0   0.0
7     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0
8     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0
9     0.0    0.0    0.0    1.0    1.0       1.0       0.0   0.0   0.0   1.0
10    0.0    1.0    0.0    0.0    1.0       0.0       1.0   0.0   0.0   1.0

In [136]:
x2 = dfw.iloc[:,20:]
x2

Age0  CO20      CO20       O20       HC0      Age1  CO1      CO21  \
1   0.507334   0.0  0.856125  0.098296  0.000000  0.277778  0.0  0.872340   
2   0.366348   0.0  0.769332  0.004187  0.523355  0.222222  0.0  1.000000   
3   0.200590   0.0  0.976205  0.048142  0.066863  0.000000  0.0  0.989362   
4   0.830721   0.0  0.529584  0.163548  0.051920  0.722222  0.0  0.521277   
5   0.636347   0.0  0.768920  0.031817  0.053029  0.500000  0.0  0.978723   
6   0.661863   0.0  0.711502  0.083836  0.220621  0.500000  0.0  0.808511   
7   0.500413   0.0  0.297865  0.066722  0.810192  1.000000  0.0  0.765957   
8   0.030114   0.0  0.007600  0.007600  0.999489  1.000000  0.0  0.000000   
9   0.740995   0.0  0.463122  0.463122  0.148199  0.944444  0.0  0.765957   
10  0.746901   0.0  0.597521  0.232857  0.175741  0.777778  0.0  0.882979   

         O21       HC1  
1   0.118357  0.000000  
2   0.000000  0.014347  
3   0.051530  0.001435  
4   0.247182  0.001435  
5   0.041868  0.001435  
6   0.115942  0.005739  
7   0.219002  0.048780  
8   0.420290  1.000000  
9   1.000000  0.005739  
10  0.420290  0.005739

In [137]:
x3 = dfw.iloc[:,25:]
x3

Age1  CO1      CO21       O21       HC1
1   0.277778  0.0  0.872340  0.118357  0.000000
2   0.222222  0.0  1.000000  0.000000  0.014347
3   0.000000  0.0  0.989362  0.051530  0.001435
4   0.722222  0.0  0.521277  0.247182  0.001435
5   0.500000  0.0  0.978723  0.041868  0.001435
6   0.500000  0.0  0.808511  0.115942  0.005739
7   1.000000  0.0  0.765957  0.219002  0.048780
8   1.000000  0.0  0.000000  0.420290  1.000000
9   0.944444  0.0  0.765957  1.000000  0.005739
10  0.777778  0.0  0.882979  0.420290  0.005739

In [138]:
x4 = dfw['Age1']
x4

1     0.277778
2     0.222222
3     0.000000
4     0.722222
5     0.500000
6     0.500000
7     1.000000
8     1.000000
9     0.944444
10    0.777778
Name: Age1, dtype: float64

In [139]:
x5 = dfw.iloc[:,26:]
x5

CO1      CO21       O21       HC1
1   0.0  0.872340  0.118357  0.000000
2   0.0  1.000000  0.000000  0.014347
3   0.0  0.989362  0.051530  0.001435
4   0.0  0.521277  0.247182  0.001435
5   0.0  0.978723  0.041868  0.001435
6   0.0  0.808511  0.115942  0.005739
7   0.0  0.765957  0.219002  0.048780
8   0.0  0.000000  0.420290  1.000000
9   0.0  0.765957  1.000000  0.005739
10  0.0  0.882979  0.420290  0.005739

In [140]:
dfx = pd.concat([x1, x4, x5], axis=1)
dfx

Make0  Make1  Make2  Make3  Fuel0  Vehicle0  Vehicle1  Use0  Use1  Use2  \
1     1.0    0.0    0.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
2     1.0    0.0    0.0    0.0    1.0       0.0       1.0   1.0   0.0   0.0   
3     0.0    0.0    1.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
4     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0   
5     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0   
6     0.0    0.0    1.0    0.0    1.0       0.0       1.0   0.0   1.0   0.0   
7     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
8     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
9     0.0    0.0    0.0    1.0    1.0       1.0       0.0   0.0   0.0   1.0   
10    0.0    1.0    0.0    0.0    1.0       0.0       1.0   0.0   0.0   1.0   

        Age1  CO1      CO21       O21       HC1  
1   0.277778  0.0  0.872340  0.118357  0.000000  
2   0.222222  0.0  1.000000  0.000000  0.014347  
3   0.000000  0.0  0.989362  0.051530  0.001435  
4   0.722222  0.0  0.521277  0.247182  0.001435  
5   0.500000  0.0  0.978723  0.041868  0.001435  
6   0.500000  0.0  0.808511  0.115942  0.005739  
7   1.000000  0.0  0.765957  0.219002  0.048780  
8   1.000000  0.0  0.000000  0.420290  1.000000  
9   0.944444  0.0  0.765957  1.000000  0.005739  
10  0.777778  0.0  0.882979  0.420290  0.005739

In [141]:
dfx.iloc[:,:11]

Make0  Make1  Make2  Make3  Fuel0  Vehicle0  Vehicle1  Use0  Use1  Use2  \
1     1.0    0.0    0.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
2     1.0    0.0    0.0    0.0    1.0       0.0       1.0   1.0   0.0   0.0   
3     0.0    0.0    1.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
4     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0   
5     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0   
6     0.0    0.0    1.0    0.0    1.0       0.0       1.0   0.0   1.0   0.0   
7     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
8     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
9     0.0    0.0    0.0    1.0    1.0       1.0       0.0   0.0   0.0   1.0   
10    0.0    1.0    0.0    0.0    1.0       0.0       1.0   0.0   0.0   1.0   

        Age1  
1   0.277778  
2   0.222222  
3   0.000000  
4   0.722222  
5   0.500000  
6   0.500000  
7   1.000000  
8   1.000000  
9   0.944444  
10  0.777778

In [142]:
dfx.iloc[:,11:]

CO1      CO21       O21       HC1
1   0.0  0.872340  0.118357  0.000000
2   0.0  1.000000  0.000000  0.014347
3   0.0  0.989362  0.051530  0.001435
4   0.0  0.521277  0.247182  0.001435
5   0.0  0.978723  0.041868  0.001435
6   0.0  0.808511  0.115942  0.005739
7   0.0  0.765957  0.219002  0.048780
8   0.0  0.000000  0.420290  1.000000
9   0.0  0.765957  1.000000  0.005739
10  0.0  0.882979  0.420290  0.005739

In [143]:
# dfw.to_excel("result.xlsx")
with pd.ExcelWriter('output.xlsx') as writer:  
    df.to_excel(writer, sheet_name='Sheet_name_1')
    dfw.to_excel(writer, sheet_name='Sheet_name_2')
    dfx.to_excel(writer, sheet_name='Sheet_name_3')

In [144]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Load the vehicle dataset
X, y = dfx.iloc[:,:11], dfx.iloc[:,11:]

# Use only one feature
# X = X[:, np.newaxis, 2]

# Split the data into training/testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(X_train, y_train)

# Make predictions using the testing set
y_pred = regr.predict(X_test)

# The coefficients
print('Coefficients: \n', regr.coef_)

# The mean squared error
print('Mean squared error: %.2f' % mean_squared_error(y_test, y_pred))

# The coefficient of determination: 1 is perfect prediction
print('Coefficient of determination: %.2f' % r2_score(y_test, y_pred))



Coefficients: 
 [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-3.08999755e-01  0.00000000e+00 -3.99241868e-02  3.48923942e-01
  -1.11022302e-16  4.08107117e-02 -4.08107117e-02 -2.20775251e-01
  -3.99241868e-02  2.60699438e-01 -1.94460748e+00]
 [-2.50465045e-01  5.55111512e-17 -1.25242934e-01  3.75707979e-01
   1.11022302e-16 -2.97767783e-03  2.97767783e-03  1.94201510e-01
  -1.25242934e-01 -6.89585763e-02  8.36331834e-01]
 [ 4.97658273e-01 -1.11022302e-16 -1.40173816e-03 -4.96256535e-01
   0.00000000e+00 -4.57626280e-03  4.57626280e-03 -4.95662857e-01
  -1.40173816e-03  4.97064595e-01  6.23361203e-03]]
Mean squared error: 0.22
Coefficient of determination: -267.97


In [16]:
# Plot outputs
plt.scatter(X_test, y_test,  color='black')
plt.plot(X_test, y_pred, color='blue', linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

ValueError: x and y must be the same size

In [160]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

X, y = dfx.iloc[:,:11], dfx.iloc[:,11:]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)

print(regr.predict(X_test[:2]))

print(regr.score(X_test, y_test))

[[ 0.00910569  1.23048312 -0.04099189 -0.16027018]
 [ 0.00943126  0.51104214  0.47085878  0.58436662]]
-219.34663478264272


In [155]:
X_train

Make0  Make1  Make2  Make3  Fuel0  Vehicle0  Vehicle1  Use0  Use1  Use2  \
3     0.0    0.0    1.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
10    0.0    1.0    0.0    0.0    1.0       0.0       1.0   0.0   0.0   1.0   
7     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
8     1.0    0.0    0.0    0.0    1.0       1.0       0.0   0.0   0.0   1.0   
1     1.0    0.0    0.0    0.0    1.0       1.0       0.0   1.0   0.0   0.0   
4     0.0    0.0    1.0    0.0    1.0       1.0       0.0   0.0   1.0   0.0   
9     0.0    0.0    0.0    1.0    1.0       1.0       0.0   0.0   0.0   1.0   

        Age1  
3   0.000000  
10  0.777778  
7   1.000000  
8   1.000000  
1   0.277778  
4   0.722222  
9   0.944444

In [146]:
y

CO1      CO21       O21       HC1
1   0.0  0.872340  0.118357  0.000000
2   0.0  1.000000  0.000000  0.014347
3   0.0  0.989362  0.051530  0.001435
4   0.0  0.521277  0.247182  0.001435
5   0.0  0.978723  0.041868  0.001435
6   0.0  0.808511  0.115942  0.005739
7   0.0  0.765957  0.219002  0.048780
8   0.0  0.000000  0.420290  1.000000
9   0.0  0.765957  1.000000  0.005739
10  0.0  0.882979  0.420290  0.005739